//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buying_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buying_Bill()
        {
            this.Buying_Bill_Details = new HashSet<Buying_Bill_Details>();
        }
    
        public int bill_id { get; set; }
        public int vend_id { get; set; }
        public System.DateTime bill_date { get; set; }
        public double bill_paid { get; set; }
        public double bill_discount { get; set; }
        public double bill_other_costs { get; set; }
        public string bill_paying_type { get; set; }
        public string bill_notes { get; set; }
        public int user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buying_Bill_Details> Buying_Bill_Details { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual User User { get; set; }
    }
}
