//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Phone
    {
        public int cust_id { get; set; }
        public string cust_phone { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
