//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Selling_Bill = new HashSet<Selling_Bill>();
        }
    
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public string cust_address { get; set; }
        public Nullable<double> cust_balance { get; set; }
        public Nullable<int> cust_score { get; set; }
        public string cust_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selling_Bill> Selling_Bill { get; set; }
        public virtual Customer_Phone Customer_Phone { get; set; }
    }
}
