//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dead_Products
    {
        public int product_id { get; set; }
        public System.DateTime process_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public string note { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> bill_id { get; set; }
        public int id { get; set; }
    
        public virtual Selling_Bill Selling_Bill { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
