//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Point_Of_SaleEntities1 : DbContext
    {
        public Point_Of_SaleEntities1()
            : base("name=Point_Of_SaleEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buying_Bill> Buying_Bill { get; set; }
        public virtual DbSet<Buying_Bill_Details> Buying_Bill_Details { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Phone> Customer_Phone { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<Paying_Motion> Paying_Motion { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Selling_Bill> Selling_Bill { get; set; }
        public virtual DbSet<Selling_Bill_Details> Selling_Bill_Details { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Dead_Products> Dead_Products { get; set; }
    }
}
