//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paying_Motion
    {
        public int paying_id { get; set; }
        public Nullable<int> entity_type { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<System.DateTime> paying_date { get; set; }
        public Nullable<double> paid_value { get; set; }
        public string paying_note { get; set; }
        public Nullable<int> bill_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Selling_Bill Selling_Bill { get; set; }
        public virtual User User { get; set; }
    }
}
