//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selling_Bill_Details
    {
        public int bill_id { get; set; }
        public int product_id { get; set; }
        public int product_quantity { get; set; }
        public double product_price { get; set; }
        public double profuct_discount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Selling_Bill Selling_Bill { get; set; }
    }
}
